name: Keep Mega Alive
# test edit 30-7-2023

on:
  workflow_dispatch: # Putting here is also fine!!
    release:
      types: [created] 
  schedule:
    - cron: '0 0 * * 0' # Run every Sunday at midnight

jobs:
  my_job:
    runs-on: ubuntu-22.04
    env:
      MEGA_PASSWORDS_CSV: ${{ secrets.MEGA_PASSWORDS_CSV }}
      STAT_PING_URL: ${{ secrets.PING_URL }} 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget libfuse2
      
    - name: Install megacmd
      run: |
        wget https://mega.nz/linux/repo/xUbuntu_22.04/amd64/megacmd-xUbuntu_22.04_amd64.deb
        sudo dpkg -i megacmd-xUbuntu_22.04_amd64.deb
        rm megacmd-xUbuntu_22.04_amd64.deb
    
    - name: Verify megacmd installation
      run: |
        if ! [ -x "$(command -v mega-version)" ]; then
          echo "MEGAcmd installation failed."
          exit 1
        fi
        echo "MEGAcmd installed successfully."
    
    - name: Create CSV file
      run: echo "$MEGA_PASSWORDS_CSV" > temp.csv
      
    - name: Run script
      run: |
        chmod u+x keep-mega-alive.sh
        ./keep-mega-alive.sh temp.csv
    
    - name: Cleanup
      run: rm temp.csv
      
    - name: Ping Healthchecks
      run: curl $STAT_PING_URL
          
